### ISSUE TITLE
Create About Page

### ISSUE THREAD

**Issue by zoeames** [nss-alumni/alumni-home#31]
# Story
As a user, when I navigate to the About Page, I would like to see the mission statement and the NSS Alumni board.

# Acceptance Criteria
**When** the user navigates to the about page
**Then** they should see all the board memebers
**And** they should see the mission statement

# Technical Details

**Comment by zoeames** [comment]
Wireframe:
![nss-alumni-boardmembers-mockup](https://user-images.githubusercontent.com/8093647/37878864-e4f1380c-3034-11e8-81b8-b2bea10980de.jpg)

**Comment by zoeames** [comment]
Mission Statement:  waiting for callan on this

**Comment by aoswalt** [comment]
From slack

> Our mission: To support NSS alumni post graduation through mentorship opportunities, continued education, and sense of community.

**Comment by zoeames** [comment]
Save Board members to Firebase collection called alumni.  Data structure:  

board member:
`
{
name: "Zoe Ames",
title: "Advisor",
cohort: "6",
email: "zoeames@gmail.com",
github: "https://github.com/zoeames",
linkedin: "https://www.linkedin.com/in/zoeames/",
isBoardMember: true
}
`

non-board member:
`
{
name: "Lauren Rouse",
title: "",
cohort: "E2",
email: "lauren.l.rouse@gmail.com",
github: "https://github.com/rousell",
linkedin: "https://www.linkedin.com/in/laurenlrouse/",
isBoardMember: false
}
`

**Comment by aoswalt** [comment]
Should email be used for the contact display of the board members?

**Comment by zoeames** [comment]
Yes email is probably best
