### ISSUE TITLE
resource to fetch events

### ISSUE THREAD

**Issue by aoswalt** [nss-alumni/alumni-home#6]
We need to have an api to fetch events.

More research is needed, but a Google calendar seems like an ideal solution - [Calendar API](https://developers.google.com/google-apps/calendar/v3/reference/)\
Otherwise, we need to decide on an approach

**Comment by aoswalt** [comment]
Fetching events is easy but requires authentications, meaning a back-end is needed for programmatic retrieval.

The [calendar events api](https://developers.google.com/google-apps/calendar/v3/reference/events/list) has **timeMin** and **maxResults** query parameters.\
https://www_googleapis.com/calendar/v3/calendars/*calendar_id*/events?maxResults=*5*&timeMin=*iso_datetime*

**Comment by aoswalt** [comment]
I set up a simple proxy on heroku for now to create a publicly accessible endpoint for the next 5 events.\
Being free heroku, it may have to spin up if it hasn't been accessed in a little while.

http://nss-alumni.herokuapp.com/api/events

**Comment by benwilburn** [comment]
How hard would it be to write a script that goes and and "accesses" it every so often

**Comment by aoswalt** [comment]
There's no real need, it usually starts working within 30 seconds or so, maybe a minute.\
I plan to add a message to the site or do something similar.

**Comment by benwilburn** [comment]
We can always just put a loading spinner on the page until it loads
