### ISSUE TITLE
Embedded Calendar

### ISSUE THREAD

**Issue by aoswalt** [nss-alumni/alumni-home#7]
An embedded calendar would give a better view at upcoming events.

With data coming from both Google Calendar and Meetup, we cannot rely only on embedding a Google Calendar.

Ongoing, it may make sense to have the calendars sync to a database to reduce hits to the apis and provide better management.

**Comment by aoswalt** [comment]
Once the calendar is fully integrated, views of events, upcoming meetings, etc. could be pulled out into filtered views.

**Comment by aoswalt** [comment]
It may make sense to have the calendar sync to a database to reduce hits to the Google api.

**Comment by john-dulaney** [comment]
Hi Adam,

Have you considered plugins for this? [FullCalendar](https://fullcalendar.io/) Seems promising, plays well with Google calendars, I'm sure bringing in external calendar data from Meetup.com (or db) wont be too much of a pain.

Pros:
Lightweight, Works with at least google, appears to be up to date (typescript support means they're hip right?)

Cons:
jQuery

**Comment by aoswalt** [comment]
Hey, John.

I am already mapping the Google and Meetup data to a common format in my proxy api, so we can map that to whatever shape makes sense.

To me, FullCalendar being jQuery instead of React is a dealbreaker. I don't want to mix UI libraries if at all possible. I knew about [react-big-calendar](https://github.com/intljusticemission/react-big-calendar) as an option, and it turns out it was inspired by FullCalendar.
